version: '3.7'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8080:443"
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./src:/var/www
        depends_on:
            - postgresql
            - redis
            - elasticsearch
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./src:/var/www
        depends_on:
            - postgresql
            - redis
            - elasticsearch
    php-cli-xdebug:
        build:
            context: ./
            dockerfile: docker/php-cli-xdebug.docker
        environment:
            - "PHP_IDE_CONFIG=serverName=Docker"
        volumes:
            - ./src:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./storage/docker/profiler:/tmp/profiler
        depends_on:
            - postgresql
            - redis
            - elasticsearch
    postgresql:
        image: postgres:11.1-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - "POSTGRES_DB=library"
            - "POSTGRES_USER=app"
            - "POSTGRES_PASSWORD=123456"
        ports:
            - "5432:5432"
    redis:
        image: redis:4.0
        ports:
            - "63791:6379"
    node:
        image: node:8.12-alpine
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        tty: true
    composer:
        image: composer:1.7
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        tty: true
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - "9201:9200"
    mongo:
        image: mongo:4.1
        ports:
            - "27017:27017"
        environment:
#            - "MONGO_INITDB_ROOT_USERNAME=app"
#            - "MONGO_INITDB_ROOT_PASSWORD=123456"
            - "MONGO_INITDB_DATABASE=library"
            - "MONGODB_USER=app"
            - "MONGODB_PASSWORD=123456"
        volumes:
            - mongo-data:/data/db

volumes:
    pgdata:
        driver: local
    elasticsearch-data:
        driver: local
    mongo-data:
        driver: local