version: '3.7'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8080:443"
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./src:/var/www
        depends_on:
            - mysql
            - redis
            - elasticsearch
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./src:/var/www
        depends_on:
            - mysql
            - redis
            - elasticsearch
    php-cli-xdebug:
        build:
            context: ./
            dockerfile: docker/php-cli-xdebug.docker
        environment:
            - "PHP_IDE_CONFIG=serverName=Docker"
        volumes:
            - ./src:/var/www
        depends_on:
            - mysql
            - redis
            - elasticsearch
    mysql:
        image: mysql:8.0
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123456"
            - "MYSQL_DATABASE=library"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=123456"
        ports:
            - "33061:3306"
    redis:
        image: redis:4.0
        ports:
            - "63791:6379"
    node:
        image: node:8.12-alpine
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        tty: true
    composer:
        image: composer:1.7
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        tty: true
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9201:9200"