version: '3.7'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8080:443"
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./src:/var/www
        depends_on:
            - postgresql
            - redis
            - elasticsearch
            - mongo
            - rabbitmq
    consumer-book-upload:
        restart: always
        command: bash -c "./artisan command:consumer-book-upload"
        build:
            context: ./
            dockerfile: docker/php-cli-xdebug.docker
        environment:
            - "PHP_IDE_CONFIG=serverName=Docker"
        volumes:
            - ./src:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./storage/docker/profiler:/tmp/profiler
        depends_on:
            - postgresql
            - rabbitmq
    consumer-send-email:
        restart: always
        command: bash -c "./artisan command:consumer-send-email"
        build:
            context: ./
            dockerfile: docker/php-cli-xdebug.docker
        environment:
            - "PHP_IDE_CONFIG=serverName=Docker"
        volumes:
            - ./src:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./storage/docker/profiler:/tmp/profiler
        depends_on:
            - postgresql
            - rabbitmq
    consumer-send-sms:
        restart: always
        command: bash -c "./artisan command:consumer-send-sms"
        build:
            context: ./
            dockerfile: docker/php-cli-xdebug.docker
        environment:
            - "PHP_IDE_CONFIG=serverName=Docker"
        volumes:
            - ./src:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./storage/docker/profiler:/tmp/profiler
        depends_on:
            - postgresql
            - rabbitmq
    php-cli-xdebug:
        build:
            context: ./
            dockerfile: docker/php-cli-xdebug.docker
        environment:
            - "PHP_IDE_CONFIG=serverName=Docker"
        volumes:
            - ./src:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./storage/docker/profiler:/tmp/profiler
        depends_on:
            - postgresql
            - redis
            - elasticsearch
            - mongo
            - rabbitmq
    postgresql:
        image: postgres:11.1-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - "POSTGRES_DB=library"
            - "POSTGRES_USER=app"
            - "POSTGRES_PASSWORD=123456"
        ports:
            - "5432:5432"
    redis:
        image: redis:4.0
        ports:
            - "63791:6379"
    node:
        image: node:8.15-alpine
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        tty: true
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - "9201:9200"
    kibana:
        #       http://localhost:5601
        image: docker.elastic.co/kibana/kibana:6.6.1
        ports:
            - "5601:5601"
        volumes:
            - ./docker/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
        depends_on:
            - elasticsearch
            - logstash
    logstash:
        #       http://localhost:9600
        image: docker.elastic.co/logstash/logstash:6.6.1
        volumes:
            - ./docker/elk/logstash/pipeline/:/usr/share/logstash/pipeline
            - ./docker/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        ports:
            - "9600:9600"
        depends_on:
            - elasticsearch
    mongo:
        image: mongo:4.0
        ports:
            - "27017:27017"
        environment:
#            - "MONGO_INITDB_ROOT_USERNAME=app"
#            - "MONGO_INITDB_ROOT_PASSWORD=123456"
            - "MONGO_INITDB_DATABASE=library"
            - "MONGODB_USER=app"
            - "MONGODB_PASSWORD=123456"
        volumes:
            - mongo-data:/data/db

    rabbitmq:
        image: rabbitmq:3.6.15-management
        environment:
            - "RABBITMQ_DEFAULT_USER=app"
            - "RABBITMQ_DEFAULT_PASS=123456"
        ports:
            - "5672:5672"
            - "15672:15672" # http://localhost:15672

volumes:
    pgdata:
        driver: local
    elasticsearch-data:
        driver: local
    mongo-data:
        driver: local